- hosts: localhost
  tasks:
    # Using kubectl rather than k8s module because the
    # k8s module only allows single document files and
    # the majority of these files are pretty straight
    # copies from upstream rook, so reorganizing them
    # into single document files is lame.
    - name: Set up Rook operator
      command: kubectl --context gitea apply -f operator.yaml
    - name: Set up Rook cluster
      command: kubectl --context gitea apply -f cluster.yaml
    - name: Set up Rook toolbox
      command: kubectl --context gitea apply -f toolbox.yaml
    - name: Set up Rook filesystem
      command: kubectl --context gitea apply -f filesystem.yaml
