- hosts: bridge.openstack.org
  name: "Bridge: configure the bastion host"
  become: true
  roles:
    - pip3
    - install-ansible
    - root-keys
    - ansible-cron
    - cloud-launcher-cron
  tasks:
    - name: Allow Zuul to trigger Ansible
      authorized_key:
        state: present
        user: root
        key: "{{ item }}"
      loop:
        - "https://zuul.openstack.org/api/project-ssh-key/openstack-infra/system-config.pub"
        - "https://zuul.openstack.org/api/project-ssh-key/openstack-infra/project-config.pub"
