- hosts: '*'
  strategy: free
  gather_facts: true
  roles:
  - role: puppet
    manage_config: True
    puppet_reports: none
    futureparser: "{{ True if 'futureparser' in group_names else False }}"
