- hosts: 'puppet4'
  gather_facts: false
  tasks:
  - git:
      repo: https://git.openstack.org/openstack-infra/system-config
      dest: /opt/system-config/production
      force: yes
  - shell: ./install_puppet.sh
    args:
      chdir: /opt/system-config/production
    environment:
      PUPPET_VERSION: 4
