# Run this with "-f 20"

- hosts: 'zuul01.openstack.org'
  tasks:
    - name: Start Zuul Scheduler
      service:
        name: zuul-scheduler
        state: started
      become: true
      become_user: root
    - name: Stop Zuul Web
      service:
        name: zuul-web
        state: started
      become: true
      become_user: root
    - name: Stop Zuul Finger Gateway
      service:
        name: zuul-fingergw
        state: started
      become: true
      become_user: root

- hosts: 'zm*.openstack.org'
  tasks:
    - name: Start Zuul Mergers
      service:
        name: zuul-merger
        state: started
      become: true
      become_user: root

- hosts: 'ze*.openstack.org'
  tasks:
    - name: Start Zuul Executors
      service:
        name: zuul-executor
        state: started
      become: true
      become_user: root
